FROM mysql:5

ENV MYSQL_ROOT_PASSWORD 123  
ENV MYSQL_DATABASE shopping  
ENV MYSQL_USER shopping  
# change this soon!
ENV MYSQL_PASSWORD 123

# bootstrap DB 
# ADD bootstrap.sql /docker-entrypoint-initdb.d 